name: 'Github Actions for teams - Team labeler action'
description: "Add a team label & code reviewers based on the author's team"
author: 'Yash Jhunjhunwala'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    required: false
    default: '.github/teams.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'blue'
